spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/feature-flag?currentSchema=public}
    username: ${SPRING_DATASOURCE_USERNAME:feature-flag}
    password: ${SPRING_DATASOURCE_PASSWORD:feature-flag123}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # Hibernate batch settings for performance
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    default-schema: public
    validate-on-migrate: false

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}

logging:
  level:
    com.featureflag: ${LOGGING_LEVEL_COM_FEATUREFLAG:ERROR}
    org.springframework.web: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB:ERROR}
    org.hibernate.SQL: ${LOGGING_LEVEL_ORG_HIBERNATE_SQL:ERROR}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOGGING_LEVEL_ORG_HIBERNATE_TYPE:ERROR}
